### ISSUE TITLE
Debugging the boilerplate

### ISSUE THREAD

**Issue by ealmz** [RadarTech/ln-api-boilerplate#19]
Hi, I've never used TypeScript before and vaguely familiar with VSCode debugging. How would I debug my app?

My launch.json currently looks like this based on the launch.json in the original repo. I get this error: `(node:37576) UnhandledPromiseRejectionWarning: TypeError: Channel expects a string, a credential and an object`
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch & Debug Application",
      "args": ["${workspaceRoot}/server/src/index.ts"],
      "runtimeArgs": ["-r", "ts-node/register"],
      "cwd": "${workspaceRoot}/server",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Debug Tests",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "--opts",
        "${workspaceFolder}/server/test/mocha.opts",
        "${workspaceFolder}/server/test/**/*.test.ts",
        "--no-timeouts"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach Debugger to Process",
      "processId": "${command:PickProcess}"
    }
  ]
}
```

**Comment by cavanmflynn** [comment]
Hey @ealmz, this error is occurring because you changed your current working directory to `"${workspaceRoot}/server"`, but the environment variables are defined in the workspace root.

You have two options to fix this issue. Either you could move the environment file (`.env`) into the `server` directory OR update your current working directory from `"cwd": "${workspaceRoot}/server",` to `"cwd": "${workspaceRoot}",`.

Also, if you would like to debug the tests (`Debug Tests`), you must update `--require test/mocha.env.ts` to `--require server/test/mocha.env.ts` in `server/test/mocha.opts`.

**Comment by ealmz** [comment]
I tried `"cwd": "${workspaceRoot}",` and it didn't not work. 

This is my output:
```
$ /Users/emmyalmaraz/.nvm/versions/node/v11.10.1/bin/node -r ts-node/register --inspect-brk=4586 /Users/emmyalmaraz/lapp/server/src/index.ts 
Debugger listening on ws://127.0.0.1:4586/440487c0-cfa3-4636-ab25-a54523d34426
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

/Users/emmyalmaraz/lapp/node_modules/ts-node/src/index.ts:228
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS2468: Cannot find global value 'Promise'.
```

Here is my file structure in case it helps.
<img width="257" alt="Screen Shot 2019-11-12 at 4 27 00 PM" src="https://user-images.githubusercontent.com/40888543/68716200-4ffe6b00-0569-11ea-8ad8-56b2ab75f2e7.png">

**Comment by cavanmflynn** [comment]
It looks like you're missing the [tsconfig.json](https://github.com/RadarTech/ln-api-boilerplate/blob/master/tsconfig.json).

Default values are used when no `tsconfig.json` is provided. The default target is `ES3`, which would explain the `Cannot find global value 'Promise'.` error.

Please add a `tsconfig.json` with a target of `es6` to fix the above error.

**Comment by ealmz** [comment]
The tsconfig.json is inside server alongside tslint.json.

**Comment by cavanmflynn** [comment]
Move it to the workspace root to fix the issue (outside of the `server` directory).

**Comment by ealmz** [comment]
It worked, thanks Cavan! I really appreciate it.
